### ISSUE TITLE
LGT8F328P vs ATmega328P - potential processor upgrade & replacement in ATS-20

### ISSUE THREAD

**Issue by diqezit** [goshante/ats20_ats_ex#42]
# Comparing ATmega328P vs LGT8F328P for SI4732 

As an alternative to the Arduino Nano 328P, the LGT8F328P microcontroller is gaining more and more attention
It remains instruction-compatible with the ATmega328P, and provides slightly higher performance with several advantages for battery-powered applications

## 1. Arduino Nano 328P Overview
![Arduino Nano 328P](https://github.com/user-attachments/assets/fa86e1e2-50c2-463b-9438-7111a29c4c9f)
- **MCU:** ATmega328P (8‑bit AVR)  
- **Clock:** 16 MHz (~16 MIPS)  
- **Memory:**  
  - Flash: 32 KB (2 KB for bootloader)  
  - SRAM: 2 KB  
  - EEPROM: 1 KB  
- **I/O:**  
  - 14 digital pins (6 PWM)  
  - 8 analog inputs (10‑bit, 1024 levels)  
- **Interfaces:** UART, I²C, SPI  
- **Power:** 5 V (recommended 7–12 V, accepts 6–20 V)  
- **Extras:** Onboard LED on D13, extensive documentation and code examples

## 2. LGT8F328P Overview
![LGT8F328P Board](https://github.com/user-attachments/assets/e8a1a3f8-e8ad-4c73-ab3b-3381a72b17a0)
- **MCU:** 8‑bit RISC‑AVR core, AVR‑instruction compatible  
- **Clock:**  
  - Internal up to 32 MHz  
  - External crystal 16 MHz supported  
- **Memory:**  
  - Flash: 32 KB  
  - SRAM: 2 KB  
  - EEPROM: emulated in Flash (configurable 1–8 KB, reduces available Flash)  
- **I/O:**  
  - 14 digital pins (6 PWM, plus extra GPIO on some packages)  
  - 8 analog inputs (12‑bit, 4096 levels)  
- **Voltage:** 1.8–5.5 V  
- **Extras:**  
  - 8‑bit DAC  
  - Internal references: 1.024 V, 2.048 V, 4.096 V  
  - Signal amplifier for ADC  
  - Extra timers (Timer3) with up to 9 PWM channels  
  - Unique ID (GUID)  
  - DSC accelerator for fast 16‑bit math  
  - PWM dead‑time control  
  - Some boards add LDO, USB‑C, Bluetooth 5.0, hardware encryption

## 3. Performance Comparison
- **Clock speed:** LGT8F328P can run at twice the frequency (32 vs. 16 MHz)  
- **Benchmarks:** At 32 MHz, LGT8F328P completes simple loops almost twice as fast as a Nano at 16 MHz  
- **DSC accelerator:** Speeds up 16‑bit operations further  
- **Setup note:** You must adjust clock prescalers to actually reach 32 MHz

## 4. Memory & EEPROM
- **Flash/SRAM** are identical: 32 KB / 2 KB  
- **EEPROM:**  
  - Nano has dedicated 1 KB  
  - LGT8F328P emulates EEPROM in Flash (≤8 KB, wear limited to ~100,000 cycles, uses part of Flash)  
- **Reliability:** Dedicated EEPROM generally endures more cycles per byte than emulation

## 5. Other Key Differences
- **Voltage range:** LGT8F328P: 1.8–5.5 V (vs. 5 V on Nano)  
- **ADC accuracy:** 12‑bit on LGT8F328P vs. 10‑bit on Nano  
- **DAC & references:** Only available on LGT8F328P  
- **Pin drive:** Up to 80 mA on some LGT8F328P pins  
- **Programming:** Some LGT8F328P boards use SWD/SWC ISP, and may need manual reset before upload  
- **Documentation:** Nano has complete, well‑translated docs; LGT8F328P docs can be sparse or in Chinese

## 6. Pin Compatibility Comparison
![Compare PinOUT](https://github.com/user-attachments/assets/6550ec10-c7eb-46d0-84f1-aac14e0ee140)

- LGT8F328P can effectively control the shutdown mode of MD8002A (pin 1 in the schematic)
- Approximately 1.5× longer battery life while maintaining all functions
-  SI4732 uses a 3.3V I²C/SPI interface, and the LGT8F328P can work directly with this voltage without level converters
- Additional LGT8F328P interrupts allow more efficient processing of SI4732 events (RDS data, signal level changes)

With almost complete software compatibility and minimal changes to existing circuitry, this replacement appears highly beneficial for portable SI4732 radio projects where power efficiency is critical.

**Comment by diqezit** [comment]
# Firmware Modification to Eliminate Audio Pops in ATS-20 Receiver (and mods)

**### There are several firmware options with updates (mod no rds v1-v2-v3.. etc) - read in detail and carefully from below**

It's certain that the hardware modification—connecting pin 1 of the MD8002A amplifier to an Arduino pin (A3 in my case, pin 25)—combined with firmware adjustments is a viable solution. I have successfully eliminated all the audio pops (clicks) that occurred when switching the Si4732's internal amplifier. This requires minor modifications to the firmware in a few key places, while ensuring that OLED display configurations remain unaffected. It is important to note that this improvement only affects the speaker output, as the 3.5mm headphone jack is connected before this amplifier in the signal chain.

## Modifications Made

1.  **Added hardware muting capability** by connecting the MD8002A amplifier's shutdown pin to an Arduino pin.
2.  **Modified configuration in defs.h**:
    ```cpp
    #define MD8002A_SHUTDOWN_PIN A3 // Amplifier MD8002A disable pin
    ```
3.  **Added amplifier control methods**:
    *   Created `safeAmpOff()` and `safeAmpOn()` to control the amplifier via the `MD8002A_SHUTDOWN_PIN`.
4.  **Updated controller initialization**:
    *   Modified `setup()` to initialize amplifier control.
5.  **Enhanced mode switching logic**:
    *   Updated `applyBandConfiguration()` to properly handle the amplifier during band changes.
    *   Added amplifier control before and after mode switching in `loop()` specifically for AM/SSB transitions.
6.  **Removed** an unnecessary call to `updateSSBCutoffFilter()` in the `doBandwidth` function to avoid OLED artifacts during interface switching.
7.  **Fixed SSB bandwidth display getting stuck** on an incorrect bandwidth.
    *   Moved bandwidth strings to PROGMEM to fix display freezing.
    *   Separated indices from strings to prevent memory fragmentation.
    *   Saved ~100 bytes of RAM.
8.  **Reduced** the lower brightness level threshold from 5 to 1.
9.  **Preserved frequency and step index before mode change**:
    *   Added a `processFreqChange` flag to prevent display artifacts when switching from AM to SSB.
    *   Removed redundant BFO frequency corrections (already handled in `doFrequencyTuneSSB`).
10. **Further Optimizations:**
    *   Optimized mode switching logic using modulo arithmetic instead of a switch-case.
    *   Enhanced `showFrequency()` function with string literal optimization and caching the `isSSB()` result.
    *   Refactored `showCharge()` by moving discharge tables to PROGMEM and removing lambda overhead.
    *   Implemented direct port manipulation for MD8002A amplifier control.
    *   Added a dynamic RSSI indicator for FM mode with a 1-second update interval.
    *   Added an FM stereo indicator showing '*' when a pilot tone is detected ([Issue #39](https://github.com/goshante/ats20_ats_ex/issues/39)).
    *   Fixed OLED artifacts during band switching by converting pointer arrays to 2D char arrays.
    *   Implemented an alternative EEPROM reset trigger using the AGC button.
    *   Optimized CW mode display and improved string operations throughout the codebase.
    *   Positioned the stereo indicator after the modulation mode at (24,0).
    *   Updated indicators only when their status changes to minimize CPU usage.

This solution effectively eliminates audio pops when switching between different modulation modes.

## Upgrade Archive with Firmware

> > > > > > > [MOD.zip](https://github.com/user-attachments/files/20579952/MOD.zip) <<<<<<<<

![img1.jpg](https://github.com/user-attachments/assets/ea14916d-9369-43f2-b8e3-53cad67bef9d)
![Image](https://github.com/user-attachments/assets/2aaa1542-ba01-4707-9ea2-e518e22eac6f)

*I plan to fix further bugs of the modification and continue its support.*

![Image showing how to connect the pins](https://github.com/user-attachments/assets/681c515e-bbb1-4213-845b-1d2d178f52b2)

//=======================================================================//

### I provide another version which implements saving FM stations in the list by disabling RDS operation

**Controls**

*   **Entering the menu:**
    *   A short press of the **MODE** button in FM mode opens the favorites menu.
*   **In the favorites menu:**
    *   **Encoder rotation** navigates through the list of stations.
    *   A **short press of the encoder** selects the station and tunes to it.
    *   The **BW** button deletes the selected station.
    *   The **BAND UP/DOWN** or **MODE** buttons exit the favorites menu.
*   **Saving a station:**
    *   A **long press of the MODE** button in FM mode saves the current station.
    *   "SAVED" is shown on the screen for 0.5 seconds.

**Implementation Features**

*   **Paged display:** Only 2 stations are displayed on the screen at a time to save space.
*   **Duplicate protection:** You cannot save the same frequency twice.
*   **Cursor auto-correction:** When the last station is deleted, the cursor automatically moves to the previous one.
*   **Frequency format:** Frequencies are stored as `XXXXX` (e.g., 101.5 MHz is stored as `10150`).
*   **Looped navigation:** The encoder scrolls through the list in a continuous loop.

//==================================Extras! =====================================//

### What has been fixed:

#### 1. `showFrequencySeek()` - Removed Command Conflict
*   **Removed:** `g_si4735.setFrequency(g_currentFrequency);`.
*   **Reason:** This command interrupted the chip's autonomous seek process, causing an audio drop-out for a few seconds.

#### 2. `configureFMMode()` - Fixed Seek Step
*   **Changed:** `setSeekFmSpacing(1)` to `setSeekFmSpacing(10)`.
*   **Reason:** A value of 1 is not allowed by the Si4735 documentation. The correct value is 10 (for 100 kHz).

#### 3. `doSeek()` - Added Synchronization After Seek
*   **Added:** After a seek is completed, the frequency is now synchronized correctly.
*   **Reason:** Ensures correct display of the found station and proper audio recovery.

**Result:**
*   Fixed the audio delay during FM seek ([Issue #46](https://github.com/goshante/ats20_ats_ex/issues/46)).
*   Station search now works correctly without conflicts.
*   Minimal code changes were made to save memory.

#### Other Fixes:
*   Aligned the 9 kHz AM seek grid by changing the MW lower band limit to 450 kHz, ensuring correct alignment for both 9kHz and 10kHz steps ([Issue #44](https://github.com/goshante/ats20_ats_ex/issues/44)).
*   Simplified battery charge calculation in `showCharge` to remove a costly 32-bit division, saving ~46 bytes.
*   Removed redundant `stepEvent` and `agcEvent` wrapper functions, saving ~16 bytes.
*   Adjusted the startup screen layout for better alignment.

**Final size: 30706 bytes**

>>>>>>>>> [MOD_NO_RDS.zip](https://github.com/user-attachments/files/20878182/MOD_NO_RDS.zip) <<<<<<<<<<<<<<<<

![Image](https://github.com/user-attachments/assets/f739a0fd-ab2a-4b07-ae84-2e2c5e6e79dc)
![Image](https://github.com/user-attachments/assets/34e9151e-504d-44f8-b910-d4e66e8fa439)

//==================================================================================//

### MOD_NO_RDS_v2 Release

Since there were many changes, I didn't incorporate them into the old MOD_NO_RDS.zip file. The new edits listed below are in a separate firmware - **MOD_NO_RDS_v2.zip**, which is a continuation of the first version.

You can download MOD_NO_RDS_v2.zip here >>>>>>>> [MOD_NO_RDS_v2.zip](https://github.com/user-attachments/files/20906209/MOD_NO_RDS_v2.zip)

**Key Improvements in v2:**

*   **Refactored Tuning Step Management:**
    1.  Replaced the global `g_stepIndex` with two independent variables for AM and SSB modes, making the state of each mode deterministic.
    2.  Converted all SSB steps to Hertz in advance and included them in a single array, simplifying the logic.
    3.  Formalized step index synchronization with EEPROM, ensuring the step setting is never lost during band or mode changes.
    4.  Rewrote the step management logic (`doStep()` and `showStep()`) to be clearer and more efficient.
*   **Improved Battery Level Display:** After freeing up Flash memory, the battery percentage calculation now uses an interpolation formula for a more accurate and smooth display, eliminating noticeable "jumps".
*   **Fixed CW Reception Mode:**
    *   Introduced `CW_PITCH_OFFSET_HZ` to automatically shift the BFO by +/- 500 Hz in CW mode. The receiver is now centered on the target frequency, while the display continues to show the actual station frequency (e.g., 7030.00 kHz). This provides a much more intuitive user experience, similar to commercial transceivers ([Issue #15](https://github.com/goshante/ats20_ats_ex/issues/15)).
*   **Smart SW Band Identification:** The receiver now displays the specific amateur or broadcast band name (e.g., "40m", "20m") instead of a generic "SW" label.
*   **Reworked Long Press Logic:** Band+/- buttons now cycle through all bands seamlessly.

//====================================================================================================//

### MOD_NO_RDS_v3 Release

This version represents a significant refactoring, introducing context-dependent settings to further enhance the user experience. Some ideas were borrowed from the ESP32 firmware by G8PTN.

Download this updated firmware version here >>>>>>>> [MOD_NO_RDS_v3.zip](https://github.com/user-attachments/files/20960123/MOD_NO_RDS_v3.zip)

**(!) Attention:** This firmware version has not yet undergone comprehensive testing and can be considered experimental.

**List of Changes in v3:**

1.  **(Changed) Settings Architecture: From Global to Context-Dependent:** Parameters like tuning step, bandwidth, and gain settings (AGC/AVC) are now saved independently for each modulation mode (AM, SSB, FM) within each band (LW, MW, SW, FM). This prevents the loss of user configurations when switching modes. A new two-dimensional matrix `g_modeSettings` now stores ATT, SoftMute, and AVC settings for AM and SSB contexts separately.
2.  **(Removed) Graphic S-meter from FM Mode:** To free up Flash memory for the new architecture, the graphic S-meter function was removed from FM mode.
3.  **(Changed) Minor Code Improvements:** Settings menu callbacks now provide immediate real-time feedback. The `band_names_packed` array was reformatted for clarity.
4.  **(Improved) Battery Monitoring System:** The system was redesigned for maximum reliability, using an IIR filter and hysteresis to eliminate flickering and provide an accurate, stable reading.
5.  **(Fixed) Encoder Data Access Safety:** Implemented a critical section (`noInterrupts()/interrupts()`) in the main loop to safely handle data from the encoder interrupt, preventing data races and incorrect step responses.
6.  **(Fixed) EEPROM Reliability with Versioning:** Implemented an EEPROM versioning system. The firmware now automatically detects outdated settings (e.g., after an update) and performs a safe, automatic reset to default values, preventing freezes or "bricking".
7.  **(Added) Animated Loading Indicator** on the startup screen.
8.  **(Fixed) Improved FM Station Seek:** The FM mode now uses more flexible SNR and RSSI thresholds to reliably lock onto weaker stations.

//====================================================================================================//

### **Updated Version: MOD_NO_RDS_v3.1**

Download here >>>>>>>> [MOD_NO_RDS_v3.1.zip](https://github.com/user-attachments/files/20962169/MOD_NO_RDS_v3.1.zip)

--- **Changelog for v3.1** ---

#### 1. (Changed) Refactored and Decomposed the Main `loop()` Function

The `loop()` function was restructured into smaller, single-responsibility helper functions (`updateEncoderState()`, `handleFavoritesMenu()`, `processEncoderActions()`, etc.) for improved clarity, maintainability, and robustness. The unreliable `skip` flag was replaced with a more predictable `bool` return value.

#### 2. (Changed) Organized and Sorted `globals.h`

The `globals.h` file was cleaned up, and all RDS-related definitions were removed.

#### 3. (Fixed) Inverted BFO Offset Logic in CW Mode

A bug in the `updateBFO()` function that caused the LSB/USB sidebands to be swapped in CW mode has been fixed. The receiver now operates correctly according to standard radio conventions. ([Reference](https://github.com/goshante/ats20_ats_ex/issues/42#issuecomment-3015265184))

#### 4. (Improved) Expanded BFO Calibration Range

Based on user feedback ([Issue #26](https://github.com/goshante/ats20_ats_ex/issues/26#issue-2665116189)), the BFO calibration range has been expanded to **+/- 2500 Hz** (`+/- 2.5 kHz`) in 100 Hz steps, allowing users to compensate for significant crystal frequency drift.

#### 5. (Fixed) Prevented BFO Hardware Limit Overrun for Improved Stability

The "chuff-free" tuning range (`BFOMax`) was reduced from 16000 to **13000**. This creates a safe buffer to ensure that the total BFO offset (tuning + calibration + CW sidetone) does not exceed the Si4732's hardware limit of `+/- 16383 Hz`, preventing unpredictable behavior.


//====================================================================================================//

### **Updated Version: MOD_NO_RDS_v3.2**

Download here >>>>>>>>  [MOD_NO_RDS_v3.2.zip](https://github.com/user-attachments/files/20966456/MOD_NO_RDS_v3.2.zip)

//====================================================================================================//

--- **Changelog for v3.2** ---


### 1. (Improved) Implemented "Snap-to-Grid" Tuning for AM/FM

In previous versions, the tuning logic was purely additive. 
If the receiver was tuned to an "off-grid" frequency (e.g., 9993 kHz) and a large tuning step (e.g., 10 kHz) was used, 
the next frequency would also be off-grid (10003 kHz). This required the user to manually switch to a smaller step to fine-tune to a standard broadcast frequency (like 10000 kHz).
The `doFrequencyTune()` function has been completely reworked to implement **step boundary alignment**, also known as "snap-to-grid".

Borrowed this functionality from the firmware https://github.com/esp32-si4732/ats-mini

*   Now, if the current frequency is not perfectly on the selected step grid, the **very first turn** of the encoder will automatically "snap" the frequency to the nearest correct grid point.
*   For example, if tuned to 9993 kHz with a 10 kHz step, a single upward turn will instantly jump to **10000 kHz**. A downward turn will jump to **9990 kHz**.
*   All subsequent turns will then proceed in perfect, clean steps from the aligned frequency.


### 2. (Reworked) Reworked Display Brightness Control

The previous 1-125 brightness scale was unintuitive and visually non-linear 

*   **Simplified 10-Step Control:** The setting is now a simple **1 to 10** scale for quick and clear adjustment.
*   **Visually-Corrected Curve:** A lightweight, non-linear (quadratic) mapping is used to ensure each of the 10 steps provides 
	a consistent and noticeable change in perceived brightness. This counteracts the OLED's natural non-linear response
*   **Optimized for Size and Speed:** The new logic was implemented using highly efficient integer math, resulting in a **reduction in firmware size** and zero performance overhead

### 3. (New) Configurable Antenna Capacitor

Added direct control over the RF input capacitor via the new CAP menu settins 
Allows optimizing performance for different antenna types

AUT (Default): Enables the capacitor for the internal ferrite antenna on LW/MW, as per original design.
Off: Disables the capacitor to prevent signal loss when using external or telescopic antennas on AM/SSB bands.


### 4. (Fixed) Attenuator System & Digital Noise Elimination

Removed AUTO AGC mode to eliminate I2C-induced digital hum.
Attenuator is now manual-only with strict, mode-aware bounds (1-37 for AM/SSB, 1-26 for FM)
Added stateful validation to cap ATT value on mode change, ensuring hardware commands are always in-spec
Default ATT on EEPROM reset is now 37 for a known, quiet start

### 5. Minor fixes in some logic

//====================================================================================================//

### **Updated Version: MOD_NO_RDS_v3.3**

Download here >>>>>>>> 

[MOD_NO_RDS_v3.3.zip](https://github.com/user-attachments/files/20984979/MOD_NO_RDS_v3.3.zip)

//====================================================================================================//

--- **Changelog for v3.3** ---

### 1. Optimisations (Flash Size Reduction)

*   `strlen8()` Optimized by using pointer arithmetic instead of array indexing, reducing code size and execution time.

*   `ilen()` Changed return type from int to uint8_t to reduce stack memory usage per call.

*   `saveFMFav()` Refactored the function to eliminate manual pre-check routine. 
	This change maintains identical EEPROM wear-leveling behavior while reducing the final firmware footprint by approximately 110 bytes.

*   `applyAgcSettings(), applyBandConfiguration(), doFrequencyTuneSSB()`: Refactored the AGC Automatic Gain Control has been optimized, 
	freeing up approximately 50 bytes of flash memory. 
	As a key improvement, the receiver is now more resilient: if it detects an invalid or corrupted ATT value from saved settings,
	it will automatically correct it to ensure stable performance.

*   `SettingParamToUI()`: Refactored the function to use a PROGMEM lookup table instead of a large if-else block and saves 4 bytes flash.

*   `Refactored Command Mode Logic`: Replaced four boolean flags (g_cmdVolume, g_cmdStep, etc.) with a single enum state variable. 
	This change simplifies state management and saves approximately 30 bytes of flash memory 
	by using a more efficient switch statement instead of a long if-else chain.

*   `showBandwidth()`: Refactored to apply the DRY (Don't Repeat Yourself) principle. 
	The `if-else` block now only selects the correct data source (table and index), while the memory copy operation (`strcpy_P`) is performed only once. 
	This consolidation eliminates redundant code and reduces the firmware footprint.

### 2. Fixes

*   `splitFreq()`: Fixed bug in BFO calculation (in Utils.h) by using signed integer math (int32_t).
	Prevents incorrect frequency display with negative BFO values.
	
*   `doBandwidth()`: Corrected inverted encoder direction for FM bandwidth selection. 
	A clockwise turn now properly increases the bandwidth.
 
*   `processButtonEvents()`: Removed the `Sync` toggle function from the long-press event of the `AGC` button. 
	This resolves a conflict and frees up the long-press action for future features. 
	`Sync` control remains available in the main settings menu.
	
*   The AUTO mode for attenuation (ATT) is now the default setting same as before in early versions.

### 3. Code Refactoring & Improvements

*   `processButtonEvents()`: Refactored the monolithic button processing function by SRP `static inline` functions (e.g., `handleEncoderButton`, `handleModeButton`)
	Functionality stays the same as before.


//=====================================================//


Thank you all for your participation in the discussion! 
To keep this thread focused on modifications not related to the original author's firmware, I suggest that further discussion of new versions and modifications be moved to my firmware fork

Starting with v3.3, you can find all current changes, fixes and new features at the link below.

I'll be glad to get your feedback and suggestions there!

https://github.com/diqezit/ats20_ats_ex

**Comment by EA5JXP** [comment]
Hi diqezit: I have implemented your audio pops fix. It works fine but the display also goes down every time the md8002a does, and come back to life with the amplifier. I dont know if it is normal behaviour or any thing goes wrong with my fix...

**Comment by diqezit** [comment]
> Hi diqezit: I have implemented your audio pops fix. It works fine but the display also goes down every time the md8002a does, and come back to life with the amplifier. I dont know if it is normal behaviour or any thing goes wrong with my fix...

No, that's not a normal work. Try reset the memory eeprom after flashing

**Comment by EA5JXP** [comment]
As soon as I flashed the Arduino I reseted the eeprom, but I'll reset it again

**Comment by diqezit** [comment]
> As soon as I flashed the Arduino I reseted the eeprom, but I'll reset it again

Fixed the calls, and updated the modification - try updating the firmware.

The only audio clicks left are in switching mode AVC for SSB will be the next fix if possible. 

And there is also incorrect operation of the click encoder when searching for stations, when it finds a station there is no sound - bug from original

**Comment by jh4vaj** [comment]
I tried the MOD_NO_RDS firmware. 
Audio pop suppression and FM station memory functionality are working properly. 
However, SSB demodulation doesn't seem to function. 

I've uploaded a video to YouTube demonstrating the issue 
— the first half shows goshante’s ATS_EX, followed by diqezit’s MOD_NO_RDS, and finally switching back to the goshante’s ATS_EX. 

https://youtu.be/6cBegABY1NQ

I’m not sure how to fix this problem, so I’m simply sharing what I’ve observed.

**Comment by diqezit** [comment]
> I tried the MOD_NO_RDS firmware. Audio pop suppression and FM station memory functionality are working properly. However, SSB demodulation doesn't seem to function.
> 
> I've uploaded a video to YouTube demonstrating the issue — the first half shows goshante’s ATS_EX, followed by diqezit’s MOD_NO_RDS, and finally switching back to the goshante’s ATS_EX.
> 
> https://youtu.be/6cBegABY1NQ
> 
> I’m not sure how to fix this problem, so I’m simply sharing what I’ve observed.

Hi, nice to see you did a review! 

Indeed when modifying I forgot to unscramble the call g_si4735.queryLibraryId() without it the SSB will not work .

But now we need to free 70 more bytes of memory - you can temporarily comment out the greeting for the test.

```
void loadSSBPatch() {

  safeAmpOff();
  
  // This works, but i am not sure it's safe
  //g_si4735.setI2CFastModeCustom(700000);
  g_si4735.setI2CFastModeCustom(500000);
  g_si4735.queryLibraryId();  // this uncomment!
  g_si4735.patchPowerUp();
  delay(50);
  g_si4735.downloadCompressedPatch(ssb_patch_content, sizeof(ssb_patch_content), cmd_0x15, sizeof(cmd_0x15));
  g_si4735.setSSBConfig(g_bwSSBIdx[g_bwIndexSSB], 1, 0, 1, 0, 1);
  g_si4735.setI2CStandardMode();
  g_ssbLoaded = true;
  g_stepIndex = 0;

  safeAmpOn();
}
```


It may be clearing internal buffers..... or sets flags that signal readiness for more complex operations or resets some status register ( idk )

Without this command, the chip is left in an intermediate, “undefined” state.

Although from the program's point of view it was not necessary (perhaps Goshante probably had doubts too, but left it).

//================================

Try again -updated the firmware in NO_RDS this should work


Had simplify function in showcharge a bit, specifically with the charge calculation, will now be counted by the allowable lower limit due to memory shortages

**Comment by jh4vaj** [comment]
Thank you, I gave it a try. 
Since the code won’t compile under the Nano board setting (it throws a compile error), 
I switched to the UNO setting instead. 
My Nano uses the Optiboot bootloader, so I believe using the UNO configuration is fine
—in fact, that's how I've always built it without issues.

However, in this test, the ATS-20+ ends up stuck in a reboot loop. 
It might be that the binary is too large and corrupting memory.
I've uploaded a video to YouTube showing the reboot behavior (unlisted video).

https://youtu.be/Vv14DVetGHw

![Image](https://github.com/user-attachments/assets/fda744eb-bf72-4e83-9dc1-1945436313c3)

**Comment by jh4vaj** [comment]
Apologies — after downloading and compiling the latest MOD_NO_RDS firmware, the ATS-20+ now boots up correctly. SSB demodulation also seems to be working fine.

Please note that I'm using the Arduino Uno board setting. It wouldn't compile under the Nano setting (compile error occurred).

Thanks again for the quick fix.

P.S. I really appreciate that you integrated my modification for the 9 kHz step issue.

![Image](https://github.com/user-attachments/assets/71bf89b0-1631-42f4-9e16-c300edecd1f6)

**Comment by G8PTN** [comment]
Hi,
A minor point on the CW (LSB/USB) selection.

When using the "USB" passband, the receiver tuned frequency should be set lower, and for "LSB" it should be set higher.

Examples below for Yaesu and Icom. It should be noted that the terminology for “CW” and “CW-R” are different, Yaesu CW (USB) and Icom CW (LSB), but the relationship between the selected passband and BFO frequency is the same.

<img src = "https://github.com/user-attachments/assets/ac8efa0e-f384-497e-8314-eae82169f6e4" alt="drawing" width="95%"/>

The dial frequency always shows the transmitted carrier frequency. The use of CW (LSB/USB) passband provides the ability to remove unwanted interference signals as shown above.

At the moment, the code increases the frequency for CW (USB).

<img src = "https://github.com/user-attachments/assets/fdf490cc-a087-4644-9373-24be41be44d7" alt="drawing" width="50%"/> 

73, Dave       

---
<ins>**GENERAL INFORMATION**<ins>

Whilst experimenting with the ATS-MINI firmware, I came across several behavioural quirks and limitations with the SI4732 based receivers, and more have been identified by Max Arnold during the ats-mini firmware development.

These are not major issues, but a few are covered below for information purposes.
Most if not all of these points have been covered in the Issues/Discussions on the GitHub repository for ats-mini.
Path:  https://github.com/esp32-si4732/ats-mini

### Frequency control and accuracy

<ins>**BFO calibration**<ins>

The global BFO calibration offset does not work very well.
The required offset value needs to be different depending on the tuned frequency.
Example: 32.768 kHz reference 50ppm (1.6384 Hz) off frequency.
The required BFO offset required such that the “dial frequency” (display) matches the actual transmitted frequency of the station would need to be as shown below.

| Dial Frequency| BFO Offset required |
| ----------- | ----------- |
| 1 MHz | 50 Hz (50 ppm) |
| 10 MHz | 500 Hz (50 ppm) |
| 30 MHz | 1500 Hz (50 ppm) |

One user reported that his ATS-20+ was 2kHz off frequency.
https://github.com/goshante/ats20_ats_ex/issues/26#issue-2665116189

The +/- 600 Hz BFO calibration offset range may not be adequate, depending on the 32.768kHz offset.

<ins>**Chuff free tuning and SI4732 BFO range**<ins>

The specified +/-16383 Hz BFO tuning range for the SI4732 should not be exceeded. The parameter is configured as a 16-bit signed integer.

<img src = "https://github.com/user-attachments/assets/b8b661b3-6a32-4318-ac4f-2d6b48e1270a" alt="drawing" width="70%"/>

If the value sent to the SI4732 exceeds the valid range, I believe the value it uses will be clamped to +/- 16383.
The BFO value sent to the SI4732 includes the “chuff” free tuning mechanism, BFO calibration offset, and CW side-tone offset.
In the ATS_EX firmware, the “chuff” free tuning mechanism can offset the BFO by +/- 16000 Hz.
In this case, the BFO calibration offset + CW side-tone offset should not exceed 383 Hz for correct behaviour.
The “chuff” free range should be reduced to account for the BFO calibration and CW side-tone offsets.
On the Max Arnold ats-mini firmware the Calibration offset range is +/- 2kHz and the “chuff” free range is set at +/- 14 kHz.
If an offset is included for the CW side-tone, then further adjustment would need to be considered.

<ins>**SI4732 frequency synthesiser accuracy**<ins>

I have noticed that the actual tuning accuracy of the SI4732 synthesiser can vary by several hundred Hz depending on the selected dial frequency. This is likely to be determined by the fractional divider parameters inside the SI4732 hardware.

<ins>Summary<ins>

- A global BFO calibration parameter does not work particularly well.
Storing values on a per band basic helps (assuming narrow band ranges).
Ideally, the reference oscillator (XTAL) frequency needs to be adjusted to be as close to nominal as possible, or a more accurate reference should be used.

    The BFO calibration adjustment range of +/- 600Hz may not be sufficient for the upper HF bands as reported by some users.

- The “chuff” free tuning range needs to take account of any offsets that will be added.
The maximum range sent to the SI4732 BFO is +/-16383 Hz.

- The actual frequency accuracy of the SI4732 synthesiser has some uncertainly. Measured variations of several hundred Hz.

The fine-tuning mechanism using the BFO works well, and it does improve the overall tuning experience.
The information from the SSB application note implies that the BFO resolution is accurate to 8Hz.

Unfortunately, I do not believe that the SI4732 was specifically designed with SSB/CW reception in mind, and therefore expecting an accurate “dial frequency” is a little unrealistic in practice.


### Parameter limits

In some cases the valid parameter ranges for particular modes are different.
Example: AGC/ATTN
FM: Range = 0 to 26

<img src = "https://github.com/user-attachments/assets/3a8b2915-8794-433e-ad5c-cefcedfea7ea" alt="drawing" width="70%"/>

AM: Range = 0 to 37

![Image](https://github.com/user-attachments/assets/b11223f2-293e-466a-97bc-e71ce780700f)

If an out-of-range value is used, the behaviour is undefined. When I experimented with FM, selecting values of 28~29 put the SI4732 into a strange state (no reception) and required a mode change or power cycle to recover.

Note: For SSB, only AGC = ON and ATTN = 0 appear to have any effect. With AGC ON, a tone is audible, which may be some sort of limitation with the SSB patch.

### Auto Capacitor
The SI4732 incorporates a variable capacitor on the RF input. This can be useful for LW/MW reception when using a ferrite loop type antenna. The capacitor is set to automatic mode for LW and MW band types.
If a loop antenna is not used, the reception performance will be degraded.
It may be worthwhile adding a configuration option to enable/disable the auto capacitor mode.
In the Max Arnold ats-mini firmware the auto capacitor has been disabled.

### Manual tuning alignment to step boundaries
In manual tuning, the frequency is not automatically aligned to the selected step boundary. In most cases, it is more convenient to align the frequencies to the step boundaries.
This is covered in the Max Arnold ats-mini firmware.

**Comment by diqezit** [comment]
Hi Dave,

Thank you for your incredibly helpful and detailed analysis. Your feedback was spot-on

Everything is now working perfectly as you described.

**Comment by jh4vaj** [comment]
I noticed that a new version of MOD_NO_RDS has been released—its progress is truly impressive.

On the MW band, I encountered an unexpected issue.

During reception, audio from a specific station broadcasting at 954 kHz is mixed in, no matter which station I tune into. 
Even when receiving 594 kHz, 693 kHz, or 810 kHz, the 954 kHz audio can always be heard simultaneously.

When tuned to 954 kHz, the audio is severely distorted.

This issue occurs only when using a small loop antenna (donut antenna). 
It does not happen when using a telescopic antenna or a larger external antenna.

I was able to receive signals normally with the goshante firmware or earlier versions of MOD_NO_RDS. 
I haven't tested MOD_NO_RDS v2, v3, or v3.1—only v3.2 I tested. 
The comment at the beginning of the v3.2 source code still indicates "v3.1," so I'm unsure whether it truly is v3.2.

![Image](https://github.com/user-attachments/assets/8b4b200a-f068-4678-8a92-a1ca0507a8bc)

**Comment by diqezit** [comment]
> On the MW band, I encountered an unexpected issue.
> 
> During reception, audio from a specific station broadcasting at 954 kHz is mixed in, no matter which station I tune into. Even when receiving 594 kHz, 693 kHz, or 810 kHz, the 954 kHz audio can always be heard simultaneously.
> 
> When tuned to 954 kHz, the audio is severely distorted.
> 
> This issue occurs only when using a small loop antenna (donut antenna). It does not happen when using a telescopic antenna or a larger external antenna.

This was a problem in version 3.2 starting in v3, when I made experimental changes to the ATT settings (was only in settings 1 - 37 (1 - 26 FM)
Wanted to remove the AUTO (0) mode to reduce background noise , but it inevitably made the receiver run at maximum sensitivity, which caused the very overload problem you describe, especially in areas with strong MW stations

In the new version v3.3 I have restored AUTO mode as a setting as originally provided in the original firmware so this should fix the problem

**Comment by jh4vaj** [comment]
I tested v3.3 and found that the issue of hearing two stations simultaneously has been resolved. Thank you very much!

I also confirmed that when setting ATT to a low value (such as 1), the issue still occurs. This proves that your judgment was spot-on.

Additionally, I’ve encountered a few other questions, but I couldn’t submit them since the forked repository doesn’t appear to have the Issues tab. I’ll report them once it becomes available.

**Comment by hagen-git** [comment]
> As an alternative to the Arduino Nano's ATmega328P, the LGT8F328P microcontroller is gaining significant attention. It is instruction-compatible with the ATmega328P and offers higher performance along with several advantages, particularly for battery-powered applications.

How about replacing the original `Arduino Nano` with pin-compatible alternatives that have more memory?

| Platform | SoC | F(clock) | Flash | RAM | EEPROM |
| ----        | ---- | ----: | ----: | ----: | ----: |
| [Arduino Nano](https://docs.arduino.cc/hardware/nano/) | ATmega328P | 16MHz | 32kB | 2kB | 1024 byte |
| [Arduino Nano Every](https://docs.arduino.cc/hardware/nano-every/) | ATmega4809 | 20MHz| 48KB | 6kB |  256 byte |
| [Arduino Nano R4](https://docs.arduino.cc/hardware/nano-r4/) | RA4M1 (ARM core) | 48MHz | 256kB | 32kB | 8192 byte |

-> The `Arduino Nano R4` looks very interesting to me.

Questions to the forum:
- Did anyone already try this?
- Are there important libraries missing for the Nano R4?
- Are there hardware limitations of the Nano R4 in comparison to the 'normal' Nano??

NB: I don't know if the ATmega4809 is fully instruction-compatible with the ATmega328. The Nano R4 32-bit-ARM-M4 code is not, of course, and it will likely need more space than the 8-bit-AVR code of the other platforms. But a recompile is not a big problem.
